### ISSUE TITLE
Recommended GPU for Inference?

### ISSUE THREAD

**Issue by dongzizhu** [hyn2028/llm-cxr#16]
Hi, thanks for the great work and all the detailed notes. I've successfully run the code. Now I want to perform some inference on my own dataset, yet it seems the code is only using the CPU, even though I do assign a GPU for the task. Is it because the GPU is not large enough and thus the code automatically falls back into the CPU version? Is there a way to check if it is running on the CPU or the GPU?

Thx in advance!

**Comment by dongzizhu** [comment]
Ok I just realized it's because the cuda is not available for some reason... I just did the "conda env create" as in your readme.md. Any suggestion?

**Comment by hyn2028** [comment]
Hello @dongzizhu, 

As stated below in the README, any NVIDIA GPU with VRAM of 11GB or more can be easily inferred with the model. 

> We recommend using a GPU with at least 11GB of memory such as NVIDIA GeForce GTX 1080 Ti 11GB or higher.

In principle, when you install the environment using `conda env create --file environment.yaml`, the CUDA environment should be installed automatically. Does `torch.cuda.is_available()` return `False` even if you enable the `llm-cxr` conda virtual environment? What GPU are you using?

**Comment by dongzizhu** [comment]
Yes yes, it was not available in the beginning for some reason. I fixed it by reinstalling the environment. Thx!
